# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         {{foreground}}
background         {{background | lighten(0.035)}}
cursor             {{cursor}}

active_tab_foreground     {{background | lighten(0.035)}}
active_tab_background     {{color10}}
inactive_tab_foreground   {{foreground}}
inactive_tab_background   {{background | lighten(0.035)}}

active_border_color   {{color10}}
inactive_border_color {{background | lighten(0.035)}}
bell_border_color     {{color14}}

color0      {{color0 | lighten(0.06)}}
color1      {{color1 | lighten(0.08)}}
color2      {{color2 | lighten(0.08)}}
color3      {{color3 | lighten(0.08)}}
color4      {{color4 | lighten(0.08)}}
color5      {{color5 | lighten(0.08)}}
color6      {{color6 | lighten(0.08)}}
color7      {{color7}}
color8      {{color8 | lighten(0.08)}}
color9      {{color9 | lighten(0.08)}}
color10     {{color10 | lighten(0.08)}}
color11     {{color11 | lighten(0.08)}}
color12     {{color12 | lighten(0.08)}}
color13     {{color13 | lighten(0.08)}}
color14     {{color14}}
color15     {{color15}}
