[General]
background=assets/background.jpg
primaryColor="{{color5}}"
accentColor="{{color4}}"
autoColor=false
use24HourClock=false
backgroundColor="{{color0}}"
textColor="{{color5}}"

fontFamily=FlexRounded
fontSize=12