# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1A1B1F)
$foreground = rgb(E9EAEC)
$color0 = rgb(1E1F23)
$color1 = rgb(BAA76E)
$color2 = rgb(4C5C8A)
$color3 = rgb(A670B7)
$color4 = rgb(596FB0)
$color5 = rgb(8775BD)
$color6 = rgb(A6B3D9)
$color7 = rgb(E9EAEC)
$color8 = rgb(565C6C)
$color9 = rgb(CEBE8D)
$primary = rgb(CEBE8D)
$secondary = rgb(8495C7)
$color10 = rgb(5266A3)
$color11 = rgb(BD8FCC)
$color12 = rgb(758AC7)
$color13 = rgb(8495C7)
$color14 = rgb(98A8D7)
$color15 = rgb(E9EAEC)
