# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(24222B)
$foreground = rgb(FAE2EE)
$color0 = rgb(494851)
$color1 = rgb(415085)
$color2 = rgb(415085)
$color3 = rgb(576398)
$color4 = rgb(8178A6)
$color5 = rgb(8979A5)
$color6 = rgb(B5819A)
$color7 = rgb(F0CDDE)
$color8 = rgb(A8909B)
$color9 = rgb(576AB1)
$color10 = rgb(576AB1)
$color11 = rgb(7484CB)
$color12 = rgb(ACA0DD)
$color13 = rgb(B7A1DC)
$color14 = rgb(F2ACCE)
$color15 = rgb(F0CDDE)
