# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1B1C20)
$foreground = rgb(E7E8EB)
$color0 = rgb(1F2024)
$color1 = rgb(C4B664)
$color2 = rgb(D64274)
$color3 = rgb(B76EC4)
$color4 = rgb(5160B8)
$color5 = rgb(DD745F)
$color6 = rgb(A3ABDC)
$color7 = rgb(E7E8EB)
$color8 = rgb(575A6B)
$color9 = rgb(D4C986)
$primary = rgb(D4C986)
$secondary = rgb(E5769B)
$color10 = rgb(4A58AB)
$color11 = rgb(CB90D5)
$color12 = rgb(6D7CCF)
$color13 = rgb(E5769B)
$color14 = rgb(929DDD)
$color15 = rgb(E7E8EB)
