[General]
background=assets/background.jpg
primaryColor="#CD796F"
accentColor="#5161B8"
autoColor=false
use24HourClock=false
backgroundColor="#131418"
textColor="#CD796F"

fontFamily=FlexRounded
fontSize=12