[General]
background=assets/background.jpg
primaryColor="#8979A5"
accentColor="#8178A6"
autoColor=false
use24HourClock=false
backgroundColor="#494851"
textColor="#8979A5"

fontFamily=FlexRounded
fontSize=12