[General]
background=assets/background.jpg
primaryColor="#DD745F"
accentColor="#5160B8"
autoColor=false
use24HourClock=false
backgroundColor="#131418"
textColor="#DD745F"

fontFamily=FlexRounded
fontSize=12