# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# wallust configuration - for wallust version 3.0

# How the image is parse, in order to get the colors:
# full - resized - wal - thumb -  fastresize - kmeans
backend = "wal"

# What color space to use to produce and select the most prominent colors:
# lab - labmixed - lch - lchmixed - salience
color_space = "lch"

# NOTE: All filters will fill 16 colors (from color0 to color15), 16 color
#       variations are the 'ilusion' of more colors by opaquing color1 to color5.
# Use the most prominent colors in a way that makes sense, a scheme:
palette = "dark16"

# Ensure readable contrast by checking colors in reference to background
check_contrast = true

# Dynamically changes the threshold to be best fit for pastel tonal extraction
dynamic_threshold = true

# Do not force artificial saturation boost, respect natural image colors
# saturation = 25

[templates]
cava.template = 'colors-cava'
cava.target = '~/.config/cava/config'

hypr.template = 'colors-hyprland.conf'
hypr.target = '~/.config/hypr/wallust/wallust-hyprland.conf'

rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/wallust/colors-rofi.rasi'

firefox.template = 'colors-firefox.css'
firefox.target = '/home/fioren/.config/mozilla/firefox/s6jshzft.default-release/chrome/includes/wallust-colors.css'

waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/wallust/colors-waybar.css'

kitty.template = 'colors-kitty.conf'
kitty.target = '~/.config/kitty/kitty-themes/01-Wallust.conf'

quickshell.template = 'qml_color.json'
quickshell.target = '~/.config/quickshell/qml_color.json'

vscodium.template = 'vscode.json'
vscodium.target = '~/.config/VSCodium/User/settings.json'

swaync.template = 'colors-swaync.css'
swaync.target = '~/.config/swaync/wallust/colors-wallust.css'

sddm.template = 'sddm-theme.conf'
sddm.target = '~/.config/wallust/sddm-theme.conf'

preview.template = 'preview-theme.conf'
preview.target = '~/.config/wallust/preview-theme.conf'

#macchina.template = 'colors-macchina.toml'
#macchina.target = '~/.config/macchina/themes/wallust.toml'

#wezterm.template = 'colors-wezterm.toml'
#wezterm.target = '~/.config/wezterm/colors/wallust.toml'

#zathura.template = 'colors-zathura'
#zathura.target = '~/.config/zathura/zathurarc'

[hooks]
waybar = 'pkill -x waybar; waybar >/dev/null 2>&1 &'
kitty = 'touch ~/.config/kitty/kitty.conf; pkill -USR1 kitty 2>/dev/null || true'
swaync = 'swaync-client -rs 2>/dev/null || true'
hyprland = 'hyprctl reload 2>/dev/null || true'
cava = 'pkill -USR1 cava 2>/dev/null || true'
rofi = 'pkill -x rofi 2>/dev/null || true'

