# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

# Start virtual keyboard daemon hidden (if enabled)
exec-once = bash -c '[ ! -f "$HOME/.cache/virtual_keyboard_disabled" ] && $HOME/.local/bin/wvkbd-mobintl -L 300 -H 350 --hidden'
