# User Keybindings
# Author: Fioren (@Leshoraa)

$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts
$UserConfigs = $HOME/.config/hypr/UserConfigs

#  IMPORTANT: If you want to remap and existing keybind you MUST unbindd it first 

# The bindings are CASE SENSITIVE. We suggest you copy the exisitng binding here
#  Then change `bindd` to `unbind`

# E.g. 
# unbind = $mainMod, Return, Open terminal, exec, $term
# bindd = $mainMod, Return, Open terminal, exec, ghostty 
#
# unbind = $mainMod, E, file manager, exec, $files
# bindd = $mainMod, T, file manager, exec, $files

# If you are ADDING a bindd, make sure you include the description 
# Other the keybind search menu might not show it properly 

# E.g.
# bindd = $mainMod, Z, My z app, exec APPNAME

# Toggle Virtual Keyboard for Tablet Mode (Enable/Disable)
unbind = $mainMod, K
bindd = $mainMod, K, Toggle tablet virtual keyboard on/off, exec, $UserScripts/VirtualKeyboardToggle.sh

# Toggle Do Not Disturb (DND) for notifications / gaming
bindd = $mainMod SHIFT, N, Toggle Do Not Disturb, exec, swaync-client -d -sw

# Screen OCR (Super + Shift + O)
unbind = $mainMod SHIFT, O
bindd = $mainMod SHIFT, O, Screen OCR to Clipboard, exec, $UserScripts/ScreenOCR.sh

# Quick Project Switcher (Super + Shift + P)
bindd = $mainMod SHIFT, P, Quick Project Switcher, exec, $UserScripts/RofiProjects.sh

# Pin / Sticky Floating Window (Super + Alt + P)
bindd = $mainMod ALT, P, Pin or unpin floating window, exec, $UserScripts/PinWindow.sh

