# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# User Settings
# This is where you put your own settings as this will not be touched during update 
# if the upgrade.sh is used.

# refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/
# NOTE: some settings are in ~/.config/hypr/UserConfigs/UserDecorAnimations.conf
#
# Look on ~/.config/hypr/configs/SystemSettings.conf to know how to modify this

input {
    touchpad {
        disable_while_typing = false
        natural_scroll = false 
        clickfinger_behavior = true
        middle_button_emulation = true
        tap-to-click = true
        drag_lock = 1
    }

    touchdevice {
        enabled = false
        output = eDP-1
    }
    tablet {
        output = eDP-1
    }
}

gestures {
    workspace_swipe_distance = 300
    workspace_swipe_invert = true
    workspace_swipe_min_speed_to_force = 10
    workspace_swipe_cancel_ratio = 0.3
    workspace_swipe_create_new = true
    workspace_swipe_forever = true
    workspace_swipe_touch = true
}

# Touchpad Multi-Finger Gestures (Hyprland 0.56+)
# 3 Fingers: Workspace Swipe, Overview & Scratchpad
gesture = 3, horizontal, workspace
gesture = 3, up, dispatcher, global, quickshell:overviewToggle
gesture = 3, down, dispatcher, togglespecialworkspace

# 4 Fingers: Control Center, App Launcher & Moving Windows
gesture = 4, up, dispatcher, exec, swaync-client -t -sw
gesture = 4, down, dispatcher, exec, pkill -x rofi || rofi -show drun
gesture = 4, left, dispatcher, movetoworkspace, +1
gesture = 4, right, dispatcher, movetoworkspace, -1

render {
    direct_scanout = 1
}

cursor {
    inactive_timeout = 3
    hide_on_key_press = true
    hide_on_touch = true
}
