# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #B7A1DC # text und line
background         #07080D
cursor             #A9A6CF

active_tab_foreground     #24222B
active_tab_background     #FAE2EE
inactive_tab_foreground   #FAE2EE
inactive_tab_background   #24222B

active_border_color   #FAE2EE
inactive_border_color #24222B
bell_border_color     #415085

color0      #494851
color1		#8178A6
color2		#8178A6
color3		#B5819A
color4		#8178A6
color5		#8178A6
color6		#A8909B
color7		#B7A1DC # sub hardware & logo
color8		#8979A5
color9		#8979A5
color10		#8979A5
color11		#8979A5
color12		#8979A5
color13		#B7A1DC
color14		#F2ACCE
color15		#F0CDDE
