# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E7E8EB
background         #1B1C20
cursor             #E7E8EB

active_tab_foreground     #1B1C20
active_tab_background     #4A58AB
inactive_tab_foreground   #E7E8EB
inactive_tab_background   #1B1C20

active_border_color   #4A58AB
inactive_border_color #1B1C20
bell_border_color     #929DDD

color0      #212226
color1      #C9BC70
color2      #D9517F
color3      #BD7AC9
color4      #5F6DBE
color5      #E07F6C
color6      #AAB2DF
color7      #E7E8EB
color8      #646777
color9      #D7CD90
color10     #5865B2
color11     #CF99D8
color12     #7986D3
color13     #E781A3
color14     #929DDD
color15     #E7E8EB
