add_newline = true

format = """
[╭─](12)[](15)\
$os\
[](bg:10 fg:15)\
$directory\
[](fg:10)
[╰─](12)$character"""

[os]
disabled = false
style = "bg:15 fg:1"
symbols.Arch = "   "

[directory]
style = "bg:10 fg:15"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"
read_only = " 󰌾 "

[directory.substitutions]
"~" = " ~"

[character]
success_symbol = "[❯](bold 14)"
error_symbol = "[❯](bold red)"