add_newline = true

format = """
[╭─](10)[](14)\
$os\
[](bg:10 fg:14)\
$directory\
[](fg:10)
[╰─](10)$character"""

[os]
disabled = false
style = "bg:14 fg:0"
symbols.Arch = "   "

[directory]
style = "bg:10 fg:15"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"
read_only = " 󰌾 "

[directory.substitutions]
"~" = " ~"

[character]
success_symbol = "[❯](bold 14)"
error_symbol = "[❯](bold red)"